# Generated by Django 5.1.4 on 2025-01-16 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('task_text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('status_text', models.CharField(max_length=15)),
                ('priority_text', models.CharField(max_length=10)),
                ('deadline_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='deadline date')),
            ],
        ),
    ]
